FROM oraclelinux:9

LABEL org.opencontainers.image.authors="info@percona.com"

RUN dnf -y update; \
    dnf -y install glibc-langpack-en

ENV PPG_VERSION 15.19-1
ENV OS_VER el9
ENV FULL_PERCONA_VERSION "$PPG_VERSION.$OS_VER"

# check repository package signature in secure way
RUN set -ex; \
    export GNUPGHOME="$(mktemp -d)"; \
    gpg --batch --keyserver keyserver.ubuntu.com --recv-keys 4D1BB29D63D98E422B2113B19334A25F8507EFA5 99DB70FAE1D7CE227FB6488205B555B38483C65D; \
    gpg --batch --export --armor 4D1BB29D63D98E422B2113B19334A25F8507EFA5 > ${GNUPGHOME}/PERCONA-PACKAGING-KEY; \
    gpg --batch --export --armor 99DB70FAE1D7CE227FB6488205B555B38483C65D > ${GNUPGHOME}/RPM-GPG-KEY-centosofficial; \
    rpmkeys --import ${GNUPGHOME}/PERCONA-PACKAGING-KEY ${GNUPGHOME}/RPM-GPG-KEY-centosofficial; \
    dnf install -y findutils; \
    curl -Lf -o /tmp/percona-release.rpm https://repo.percona.com/yum/percona-release-latest.noarch.rpm; \
    rpmkeys --checksig /tmp/percona-release.rpm; \
    rpm -i /tmp/percona-release.rpm; \
    rm -rf "$GNUPGHOME" /tmp/percona-release.rpm; \
    rpm --import /etc/pki/rpm-gpg/PERCONA-PACKAGING-KEY; \
    #percona-release setup -y ppg15; \
    percona-release enable ppg-15.17;

RUN set -ex; \
    dnf -y update; \
    dnf -y install \
        bind-utils \
        gettext \
        hostname \
        perl \
        tar \
        bzip2 \
        lz4 \
        procps-ng; \
    dnf -y install  \
        nss_wrapper \
        shadow-utils \
        libpq \
        libedit; \
    dnf clean all

# the numeric UID is needed for OpenShift
RUN useradd -u 1001 -r -g 0 -s /sbin/nologin \
            -c "Default Application User" postgres

ENV PGDATA /data/db

RUN set -ex; \
    dnf install -y \
        percona-postgresql15-server-${FULL_PERCONA_VERSION} \
        percona-postgresql15-contrib-${FULL_PERCONA_VERSION} \
        percona-postgresql-common \
        percona-pg_stat_monitor15 \
        percona-pg_repack15 \
        percona-pgaudit15 \
        percona-pgaudit15_set_user \
	percona-pgvector_15 \
        percona-wal2json15; \
    dnf clean all; \
    rm -rf /var/cache/dnf /var/cache/yum $PGDATA && mkdir -p $PGDATA /docker-entrypoint-initdb.d; \
    chown -R 1001:0 $PGDATA docker-entrypoint-initdb.d

RUN set -ex; \
    sed -ri "s!^#?(listen_addresses)\s*=\s*\S+.*!\1 = '*'!" /usr/pgsql-15/share/postgresql.conf.sample; \
    grep -F "listen_addresses = '*'" /usr/pgsql-15/share/postgresql.conf.sample

COPY LICENSE /licenses/LICENSE.Dockerfile
RUN cp /usr/share/doc/percona-postgresql15/COPYRIGHT /licenses/COPYRIGHT.PostgreSQL

ENV GOSU_VERSION=1.19-13.9
RUN set -eux; \
    curl -Lf -o /tmp/gosu.rpm https://repo.percona.com/tools/yum/experimental/9/RPMS/x86_64/gosu-${GOSU_VERSION}.x86_64.rpm; \
    rpmkeys --checksig /tmp/gosu.rpm; \
    rpm -i /tmp/gosu.rpm; \
    rm -f /tmp/gosu.rpm; \
    gosu --version; \
    cp /usr/share/licenses/gosu/LICENSE /licenses/LICENSE.gosu

COPY entrypoint.sh /entrypoint.sh

VOLUME ["/data/db"]

ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 5432

USER 1001

CMD ["postgres"]
