apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: etcd
    etcd_node: etcd0
  name: etcd0
spec:
  replicas: 1
  selector:
    app: etcd
    etcd_node: etcd0
  template:
    metadata:
      labels:
        app: etcd
        etcd_node: etcd0
    spec:
      containers:
      - command:
        - /usr/local/bin/etcd
        - --name
        - etcd0
        - --listen-client-urls
        - http://0.0.0.0:2379
        - --advertise-client-urls
        - http://etcd0:2379
        image: quay.io/coreos/etcd:latest
        name: etcd0
        ports:
        - containerPort: 2379
          name: client
          protocol: TCP
        - containerPort: 2380
          name: server
          protocol: TCP
      restartPolicy: Always
