FROM percona/percona-server-mongodb:3.6

LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.name="Percona Server for MongoDB"
LABEL org.label-schema.vendor="Percona"
LABEL org.label-schema.description="Percona Server for MongoDB is our free and \
open-source drop-in replacement for MongoDB Community Edition. \
It offers all the features and benefits of MongoDB Community Edition, \
plus additional enterprise-grade functionality."
LABEL org.label-schema.license="SSPLv1"

LABEL org.opencontainers.image.title="Percona Server for MongoDB"
LABEL org.opencontainers.image.vendor="Percona"
LABEL org.opencontainers.image.description="Percona Server for MongoDB is our free and \
open-source drop-in replacement for MongoDB Community Edition. \
It offers all the features and benefits of MongoDB Community Edition, \
plus additional enterprise-grade functionality."
LABEL org.opencontainers.image.license="SSPLv1"
LABEL org.opencontainers.image.authors="info@percona.com"

LABEL org.label-schema.schema-version=${PSMDB_VERSION}
LABEL org.opencontainers.image.version=${PSMDB_VERSION}

USER 0

RUN set -ex; \
    sed -i 's/exec "$@"/exec "$@" -vvv || sleep infinity/' /entrypoint.sh; \
    curl -Lf -o /tmp/percona-mongodb-server-debuginfo.rpm https://repo.percona.com/yum/release/8/RPMS/x86_64/Percona-Server-MongoDB-36-server-debuginfo-${FULL_PERCONA_VERSION}.x86_64.rpm; \
    curl -Lf -o /tmp/percona-mongodb-shell-debuginfo.rpm https://repo.percona.com/yum/release/8/RPMS/x86_64/Percona-Server-MongoDB-36-shell-debuginfo-${FULL_PERCONA_VERSION}.x86_64.rpm; \
    curl -Lf -o /tmp/percona-mongodb-tools-debuginfo.rpm https://repo.percona.com/yum/release/8/RPMS/x86_64/Percona-Server-MongoDB-36-tools-debuginfo-${FULL_PERCONA_VERSION}.x86_64.rpm; \
    curl -Lf -o /tmp/percona-mongodb-mongos-debuginfo.rpm https://repo.percona.com/yum/release/8/RPMS/x86_64/Percona-Server-MongoDB-36-mongos-debuginfo-${FULL_PERCONA_VERSION}.x86_64.rpm; \
    curl -Lf -o /tmp/percona-mongodb-debugsource.rpm https://repo.percona.com/yum/release/8/RPMS/x86_64/Percona-Server-MongoDB-36-debugsource-${FULL_PERCONA_VERSION}.x86_64.rpm; \
    curl -Lf -o /tmp/percona-mongodb-tools.rpm https://repo.percona.com/yum/release/8/RPMS/x86_64/Percona-Server-MongoDB-36-tools-${FULL_PERCONA_VERSION}.x86_64.rpm; \
    rpmkeys --checksig /tmp/percona-mongodb-server-debuginfo.rpm /tmp/percona-mongodb-shell-debuginfo.rpm \
        /tmp/percona-mongodb-tools-debuginfo.rpm /tmp/percona-mongodb-mongos-debuginfo.rpm \
        /tmp/percona-mongodb-tools.rpm /tmp/percona-mongodb-debugsource.rpm; \
    rpm -iv /tmp/percona-mongodb-server-debuginfo.rpm /tmp/percona-mongodb-shell-debuginfo.rpm \
        /tmp/percona-mongodb-tools-debuginfo.rpm /tmp/percona-mongodb-mongos-debuginfo.rpm \
        /tmp/percona-mongodb-tools.rpm /tmp/percona-mongodb-debugsource.rpm --nodeps; \
    rm -f /tmp/percona-mongodb-server-debuginfo.rpm /tmp/percona-mongodb-shell-debuginfo.rpm \
        /tmp/percona-mongodb-tools-debuginfo.rpm /tmp/percona-mongodb-mongos-debuginfo.rpm \
        /tmp/percona-mongodb-tools.rpm /tmp/percona-mongodb-debugsource.rpm; \
    dnf install -y \
        net-tools \
        telnet \
        gdb \
        nc; \
    dnf clean all; \
    rm -rf /var/cache/dnf

VOLUME ["/data/db"]

ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 27017

USER 1001

CMD ["mongod"]
