FROM redhat/ubi8-minimal

LABEL name="Percona PostgreSQL Distribution upgrade" \
    vendor="Percona" \
    summary="Percona Distribution for PostgreSQL" \
    description="Percona Distribution for PostgreSQL is a collection of tools to assist you in managing your PostgreSQL database system" \
    maintainer="Percona Development <info@percona.com>"

RUN set -ex; \
    microdnf -y update; \
    microdnf -y install glibc-langpack-en platform-python tar; \
    microdnf clean all; \
    rm -rf /var/cache/dnf /var/cache/yum

ENV LC_ALL en_US.utf-8
ENV LANG en_US.utf-8
ARG PG_MAJOR=18

RUN set -ex; \
    export GNUPGHOME="$(mktemp -d)"; \
    gpg --batch --keyserver keyserver.ubuntu.com --recv-keys \
        4D1BB29D63D98E422B2113B19334A25F8507EFA5 \
        76FD3DB13AB67410B89DB10E82562EA9AD986DA3 \
        99DB70FAE1D7CE227FB6488205B555B38483C65D; \
    gpg --batch --export --armor 4D1BB29D63D98E422B2113B19334A25F8507EFA5 > ${GNUPGHOME}/PERCONA-PACKAGING-KEY; \
    gpg --batch --export --armor 99DB70FAE1D7CE227FB6488205B555B38483C65D > ${GNUPGHOME}/RPM-GPG-KEY-centosofficial; \
    gpg --batch --export --armor 76FD3DB13AB67410B89DB10E82562EA9AD986DA3 > ${GNUPGHOME}/RPM-GPG-KEY-oracle; \
    gpg --batch --export --armor 76FD3DB13AB67410B89DB10E82562EA9AD986DA3 > /etc/pki/rpm-gpg/RPM-GPG-KEY-oracle; \
    rpmkeys --import \
        ${GNUPGHOME}/PERCONA-PACKAGING-KEY \
        ${GNUPGHOME}/RPM-GPG-KEY-oracle \
        ${GNUPGHOME}/RPM-GPG-KEY-centosofficial; \
    curl -Lf -o /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8 https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8; \
    rpmkeys --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8; \
    microdnf install -y findutils; \
    ARCH=$(uname -m); \
    if [ "${ARCH}" = "aarch64" ]; then \
        OL8_RELEASE_RPM="oraclelinux-release-el8-1.0-38.el8.aarch64.rpm"; \
    else \
        OL8_RELEASE_RPM="oraclelinux-release-el8-1.0-16.0.1.el8.x86_64.rpm"; \
    fi; \
    curl -Lf -o /tmp/oraclelinux-release.rpm https://yum.oracle.com/repo/OracleLinux/OL8/baseos/latest/${ARCH}/getPackage/${OL8_RELEASE_RPM}; \
    curl -Lf -o /tmp/epel-release.rpm https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm; \
    curl -Lf -o /tmp/percona-release.rpm https://repo.percona.com/yum/percona-release-latest.noarch.rpm; \
    rpm --import ${GNUPGHOME}/PERCONA-PACKAGING-KEY ${GNUPGHOME}/RPM-GPG-KEY-oracle ${GNUPGHOME}/RPM-GPG-KEY-centosofficial; \
    rpmkeys --checksig /tmp/percona-release.rpm; \
    rpmkeys --checksig /tmp/oraclelinux-release.rpm /tmp/epel-release.rpm; \
    rpm -i /tmp/percona-release.rpm /tmp/oraclelinux-release.rpm /tmp/epel-release.rpm; \
    rm -rf "$GNUPGHOME" /tmp/percona-release.rpm /tmp/oraclelinux-release.rpm /tmp/epel-release.rpm; \
    sed -i 's/^enabled=1/enabled=0/' /etc/yum.repos.d/oracle-linux-ol8.repo \
                                     /etc/yum.repos.d/uek-ol8.repo \
                                     /etc/yum.repos.d/epel.repo \
                                     /etc/yum.repos.d/epel-modular.repo 2>/dev/null || true; \
    percona-release enable ppg-${PG_MAJOR} release

RUN set -ex; \
    microdnf -y install \
        bind-utils \
        gettext \
        hostname \
        python3-pyparsing \
        perl \
        libedit \
        procps-ng; \
    microdnf install -y \
        --enablerepo=ol8_baseos_latest \
        --enablerepo=ol8_appstream \
        --enablerepo=ol8_codeready_builder \
        --enablerepo=epel \
        perl-JSON \
        perl-DBD-Pg \
        libssh2 \
        libarrow \
        snappy \
        re2 \
        boost-atomic \
        boost-chrono \
        boost-date-time \
        boost-filesystem \
        boost-program-options \
        boost-regex \
        boost-serialization \
        boost-system \
        boost-thread \
        hdf5 \
        xerces-c \
        netcdf \
        libaec \
        libgta \
        freexl \
        libdeflate \
        cfitsio \
        armadillo \
        libqhull_r \
        minizip; \
    if [ "$(uname -m)" = "x86_64" ]; then \
        microdnf install -y \
            --enablerepo=ol8_baseos_latest \
            --enablerepo=ol8_appstream \
            --enablerepo=ol8_codeready_builder \
            --enablerepo=epel \
            libkml; \
    fi; \
    microdnf clean all; \
    rm -rf /var/cache/dnf /var/cache/yum

RUN set -ex; \
    ARCH=$(uname -m); \
    curl -Lf -o /tmp/gpsbabel.rpm https://yum.oracle.com/repo/OracleLinux/OL8/developer/EPEL/${ARCH}/getPackage/gpsbabel-1.6.0-3.el8.${ARCH}.rpm; \
    rpmkeys --checksig /tmp/gpsbabel.rpm; \
    rpm -i --nodeps /tmp/gpsbabel.rpm; \
    rm -f /tmp/gpsbabel.rpm

RUN set -ex; \
    microdnf -y install \
        libpq \
        percona-postgresql${PG_MAJOR//.}; \
    microdnf -y clean all; \
    rm -rf /var/cache/dnf /var/cache/yum

RUN set -ex; \
    microdnf -y install \
        percona-pgaudit${PG_MAJOR//.} \
        percona-pgaudit${PG_MAJOR//.}_set_user \
        percona-postgresql${PG_MAJOR//.}-contrib \
        percona-postgresql${PG_MAJOR//.}-server \
        percona-postgresql${PG_MAJOR//.}-libs \
        percona-postgresql${PG_MAJOR//.}-llvmjit \
        percona-wal2json${PG_MAJOR//.} \
        percona-pg_stat_monitor${PG_MAJOR//.} \
        percona-pgvector_${PG_MAJOR//.} \
        percona-pgvector_${PG_MAJOR//.}-llvmjit \
        percona-pg_tde${PG_MAJOR//.} \
        percona-pg_oidc_validator${PG_MAJOR//.} \
        percona-postgis35_${PG_MAJOR//.} \
        percona-postgis35_${PG_MAJOR//.}-client \
        percona-postgis35_${PG_MAJOR//.}-llvmjit \
        percona-postgis35_${PG_MAJOR//.}-utils \
        percona-pg_repack${PG_MAJOR//.} \
        percona-pg_cron_${PG_MAJOR//.} \
        nss_wrapper \
        lz4 \
        unzip; \
    microdnf -y reinstall tzdata; \
    microdnf clean all; \
    rm -rf /var/cache/dnf /var/cache/yum

RUN for pg_version in 17 16 15 14 13 12; do \
        percona-release enable ppg-${pg_version} release; \
        microdnf -y install --nodocs \
            percona-pgaudit${pg_version} \
            percona-pgaudit${pg_version}_set_user \
            percona-postgresql${pg_version}-contrib \
            percona-postgresql${pg_version}-server \
            percona-postgresql${pg_version}-libs \
            percona-postgresql${pg_version}-llvmjit \
            percona-wal2json${pg_version} \
            percona-pg_stat_monitor${pg_version}; \
\
        if [[ "${pg_version}" -gt 12 ]]; then \
            microdnf -y install --nodocs \
                percona-pgvector_${pg_version} \
                percona-pgvector_${pg_version}-llvmjit \
                percona-postgis35_${pg_version} \
                percona-postgis35_${pg_version}-llvmjit \
                percona-pg_repack${pg_version}; \
        fi; \
        if [[ "${pg_version}" -ge 14 ]]; then \
            microdnf -y install --nodocs \
                percona-pg_cron_${pg_version}; \
        fi; \
\
        if [[ "${pg_version}" -ge 17 ]]; then \
            microdnf -y install --nodocs percona-pg_tde${pg_version}; \
        fi; \
    done && microdnf -y clean all && rm -rf /var/cache/dnf /var/cache/yum

RUN mkdir -p /opt/crunchy/bin /pgolddata /pgnewdata /opt/crunchy/conf
COPY bin/upgrade/ /opt/crunchy/bin
COPY bin/common /opt/crunchy/bin
COPY conf/upgrade/ /opt/crunchy/conf
COPY bin/relocate-extensions.sh /usr/local/bin/relocate-extensions.sh
COPY licenses/LICENSE.txt /licenses/LICENSE.Dockerfile

RUN chown -R postgres:postgres /opt/crunchy /pgolddata /pgnewdata && \
    chmod -R g=u /opt/crunchy /pgolddata /pgnewdata

VOLUME /pgolddata /pgnewdata

ENV NSS_WRAPPER_SUBDIR="upgrade"

ENTRYPOINT ["opt/crunchy/bin/uid_postgres.sh"]

USER 26

CMD ["/opt/crunchy/bin/start.sh"]
