apiVersion: v1
kind: PersistentVolume
metadata:
    name: datadir-mysql-0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/flash/mysql/datadir-mysql-0/
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: datadir-mysql-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/flash/mysql/datadir-mysql-1/
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: datadir-mysql-2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/flash/mysql/datadir-mysql-2/
