# This Dockerfile should be used for docker official repo

# https://github.com/docker-library/official-images:
# No official images can be derived from, or depend on, non-official images
# with the following notable exceptions...
FROM debian:trixie

LABEL name="Percona Server" \
      release="8.4" \
      vendor="Percona" \
      summary="Percona Server database server" \
      description="Percona Server is a fast, stable and true multi-user, multi-threaded SQL \
                   database server. SQL (Structured Query Language) is the most popular database \
                   query language in the world. The main goals of Percona Server are speed, \
                   robustness and ease of use." \
      maintainer="Percona Development <info@percona.com>"

LABEL org.opencontainers.image.authors="info@percona.com"

# It is intentionally used another UID, to have backward compatibility with
# the previous image versions published on Docker Hub
RUN set -ex; \
    groupadd -g 1001 mysql; \
    useradd -u 1001 -r -g 1001 -s /usr/sbin/nologin \
        -m -c "Default Application User" mysql

ENV PS_VERSION 8.4.8-8-1
ENV MYSQL_SHELL_VERSION 8.4.8-1-1
ENV OS_VER trixie
ENV FULL_PERCONA_VERSION "$PS_VERSION.$OS_VER"
ENV FULL_MYSQL_SHELL_VERSION "$MYSQL_SHELL_VERSION.$OS_VER"
ENV PS_REPO testing
ENV PS_TELEMETRY_VERSION 8.4.8-8-1
ENV CALL_HOME_DOWNLOAD_SHA256 5e84d2f1a5d57f44c46e6a1f16794d649d3de09fe8021f0294bc321c89e51068
ENV CALL_HOME_VERSION 0.1
# Do not report during Docker image creation.
# Note that doing so, would create telemetry config file
# which would prevent reporting when new container is started.
# If we want to track Docker image creation as well,
# remove telemetry config file after installing packages!
ARG PERCONA_TELEMETRY_DISABLE=1

ENV DEBIAN_FRONTEND=noninteractive

# check repository package signature in secure way
RUN set -ex; \
    export GNUPGHOME="$(mktemp -d)"; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        gnupg \
        lsb-release; \
    gpg --batch --keyserver keyserver.ubuntu.com --recv-keys 4D1BB29D63D98E422B2113B19334A25F8507EFA5 99DB70FAE1D7CE227FB6488205B555B38483C65D; \
    gpg --batch --export --armor 4D1BB29D63D98E422B2113B19334A25F8507EFA5 > ${GNUPGHOME}/PERCONA-PACKAGING-KEY; \
    gpg --batch --export --armor 99DB70FAE1D7CE227FB6488205B555B38483C65D > ${GNUPGHOME}/RPM-GPG-KEY-centosofficial; \
    curl -Lf -o /tmp/percona-release.deb https://repo.percona.com/apt/percona-release_latest.generic_all.deb; \
    apt-get install -y --no-install-recommends /tmp/percona-release.deb; \
    rm -rf "$GNUPGHOME" /tmp/percona-release.deb; \
    percona-release disable all; \
    percona-release setup -y ps-84-lts; \
    percona-release enable ps-84-lts ${PS_REPO}; \
    percona-release enable telemetry ${PS_REPO}; \
    percona-release enable mysql-shell ${PS_REPO}; \
    apt-get update

RUN set -ex; \
    apt-get install -y --no-install-recommends \
        hostname \
        tzdata \
        libjemalloc2 \
        libcrack2 \
        cracklib-runtime \
        libpwquality-tools \
        tar \
        percona-server-server=${FULL_PERCONA_VERSION} \
        percona-server-rocksdb=${FULL_PERCONA_VERSION} \
        percona-mysql-shell=${FULL_MYSQL_SHELL_VERSION}; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/* /var/lib/mysql

# Create symlink for jemalloc so entrypoint script (written for RHEL paths) works
RUN set -ex; \
    mkdir -p /usr/lib64; \
    ln -sf /usr/lib/x86_64-linux-gnu/libjemalloc.so.2 /usr/lib64/libjemalloc.so.1

# purge and re-create /var/lib/mysql with appropriate ownership
RUN set -ex; \
    /usr/bin/install -m 0775 -o mysql -g root -d /var/lib/mysql /var/run/mysqld /docker-entrypoint-initdb.d; \
# comment out a few problematic configuration values
    find /etc/mysql -name '*.cnf' -print0 \
        | xargs -0 grep -lZE '^(bind-address|log|user)' \
        | xargs -rt -0 sed -Ei 's/^(bind-address|log|user)/#&/'; \
# don't reverse lookup hostnames, they are usually another container
    printf '[mysqld]\nhost_cache_size=0\nskip-name-resolve\n' > /etc/mysql/conf.d/docker.cnf; \
# allow to change config files
    chown -R mysql:root /etc/mysql; \
    chmod -R ug+rwX /etc/mysql

COPY LICENSE /licenses/LICENSE.Dockerfile

VOLUME ["/var/lib/mysql", "/var/log/mysql"]

RUN set -eux; \
    curl -fL "https://github.com/Percona-Lab/telemetry-agent/archive/refs/tags/phase-$CALL_HOME_VERSION.tar.gz" -o "phase-$CALL_HOME_VERSION.tar.gz"; \
    echo "$CALL_HOME_DOWNLOAD_SHA256 phase-$CALL_HOME_VERSION.tar.gz" | sha256sum --strict --check; \
    tar -xvf phase-$CALL_HOME_VERSION.tar.gz; \
    cp telemetry-agent-phase-$CALL_HOME_VERSION/call-home.sh .;\
    rm -rf telemetry-agent-phase-$CALL_HOME_VERSION phase-$CALL_HOME_VERSION.tar.gz; \
    chmod a+rx /call-home.sh; \
    mkdir -p /usr/local/percona; \
    chown mysql:mysql /usr/local/percona
ENV CALL_HOME_OPTIONAL_PARAMS=" -s ${OS_VER}"

COPY ps-entry.sh /docker-entrypoint.sh
COPY telemetry-agent-supervisor.sh /usr/bin/
COPY dockerdir/ /
RUN set -ex; \
    chown  mysql /usr/bin/telemetry-agent-supervisor.sh; \
    chown  mysql /usr/bin/percona-telemetry-agent; \
    chown  mysql /usr/local/percona/telemetry/history; \
    chmod ug+rwx /usr/bin/telemetry-agent-supervisor.sh; \
    chmod -R go+w /var/log/percona
ENV PERCONA_TELEMETRY_CHECK_INTERVAL=86400
ENV PERCONA_TELEMETRY_HISTORY_KEEP_INTERVAL=604800
ENV PERCONA_TELEMETRY_RESEND_INTERVAL=60
ENV PERCONA_TELEMETRY_URL=https://check.percona.com/v1/telemetry/GenericReport
ENTRYPOINT ["/docker-entrypoint.sh"]

USER mysql
EXPOSE 3306 33060
CMD ["mysqld"]
